spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
    show-sql: true

app:
  security:
    jwt:
      keystore-location: jwt-keystore.jks
      keystore-password: password
      key-alias: jwt-sign-key
      private-key-passphrase: password